### ISSUE TITLE
How do you 'require' stemmer if you absolutely have to?

### ISSUE THREAD

**Issue by fergiemcdowall** [words/stemmer#10]
I have an established project that is based on old-style node `require`s.

Is there any way to make `stemmer` play nice with common.js modules?

**Comment by fergiemcdowall** [comment]
Answering my own question- something like this should work:

```javascript
import('stemmer').then(({stemmer}) => {
  stemmer('considerations') // => 'consider'
  stemmer('detestable') // => 'detest'
  stemmer('vileness') // => 'vile'
})
```

**Comment by wooorm** [comment]
nice!

Some more info here: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c. For short: stick with the previous version, indeed use `import()`, or change to ESM (ESM supports importing CJS fine).
