### ISSUE TITLE
Question - Stemmer API multiple words

### ISSUE THREAD

**Issue by sabatale** [words/stemmer#12]
Great library! Maybe a silly question but is there any way to stemmer a whole text, like the CLI does?

`stemmer("considerations for all mankind")`

Or should we just go with a legacy loop and replace?

**Comment by wooorm** [comment]
Use a tokenizer. This project doesn't tokenize. It follows the Unix philosophy of doing one thing well.

parse-latin is a tokenizer I work on. Bu a little regex-fu can also get you there!
