### ISSUE TITLE
Incorrect stemming of word "Day"

### ISSUE THREAD

**Issue by juancarlosgarcia-arg** [words/stemmer#9]
Guys: Can you kindly check on [this](https://runkit.com/embed/o66b584ph21j). Not sure if this is affecting other words ending with "y" too or i'm doing something wrong.

**Comment by wooorm** [comment]
> The stem need not be identical to the morphological root of the word; it is usually sufficient that related words map to the same stem, even if this stem is not in itself a valid root
> — https://en.wikipedia.org/wiki/Stemming
